pre_process:
  output_shape: [254, 384]
  adaptive_histogram:
    adaptive_histogram: True
    clip_limit: 0.05
  gray_scale: True
  train_directories: ["Data/balanced_train1"]
  test_directories: ["Data/balanced_test1"]
  valid_directories: ["Data/balanced_valid1"]
  label_file: "Data/trainLabels.csv"
  save_pre_process: False
  hdf5_file: "Data/hdf5/data_binary_balanced.hdf5"
