pre_process:
  output_shape: [256, 256]
  adaptive_histogram:
    adaptive_histogram: True
    clip_limit: 0.05
  gray_scale: True
  train_directories: ["Data/train001"]
  test_directories: []
  valid_directories: []
  image: "Data/selected_image.pkl"
  label_file: "Data/trainLabels.csv"
  save_pre_process: False
  hdf5_file: "Data/hdf5/data_binary_new.hdf5"