pre_process:
  output_shape: [1024, 1536]
  adaptive_histogram:
    adaptive_histogram: True
    clip_limit: 0.05
  gray_scale: True
  train_directories: ["Data/train001"]
  test_directories: ["Data/test001"]
  valid_directories: ["Data/valid001"]
  label_file: "Data/trainLabels.csv"
  save_pre_process: False
  h5py_directory: "Data/h5py"
