pre_process:
  output_shape: [1024, 1536]
  adaptive_histogram:
    adaptive_histogram: True
    clip_limit: 0.05
  gray_scale: True
  directories: ["Data/train001", "Data/train002"]
  label_file: "Data/trainLabels.csv"
  save_pre_process: False
