pre_process:
  output_shape: [1024, 1536]
  adaptive_histogram:
    adaptive_histogram: True
    clip_limit: 0.05
  gray_scale: True
  train_directories: ["Data/sample_train"]
  test_directories: ["Data/sample_test"]
  valid_directories: ["Data/sample_valid"]
  label_file: "Data/trainLabels.csv"
  save_pre_process: False
  hdf5_directory: "Data/hdf5"
